### ISSUE TITLE
Can't load designs with KiCad stable

### ISSUE THREAD

**Issue by omerk** [solderparty/flexypin_adapters_hw#1]
Using a fresh install of KiCad 6.0.2 (latest stable), this pops up while opening the design files:

```
Error loading PCB '<...>\ESP32-C3-WROOM_flexypin.kicad_pcb'.

Cannot interpret date code 20221232 in '<...>\ESP32-C3-WROOM_flexypin.kicad_pcb', line 134, offset 8.
```

Presumably you're using nightlies? Might be worth mentioning this in the README as KiCad itself is not being super helpful there with the error message.

**Comment by arturo182** [comment]
Yes, I used nightlies. You might be able to hack it by changing the date in the first line of the pcb file using a text editor. Not sure what date the stable uses, but you can check by opening any pcb created by stable. Let me know if that helps :)

**Comment by omerk** [comment]
I just grabbed the latest nightly build and opened the files, no issues there. Just a quick note on README might be helpful for folks who will be downloading KiCAD just to open these files though (in case they didn't have it installed already) so they can pick the right option.
