### ISSUE TITLE
Required KiCad version

### ISSUE THREAD

**Issue by Maff-** [solderparty/flexypin_adapters_hw#2]
Hey, I'v ordered some of these adapter boards and flexy pins on Lectronz. (They're nice btw, so thanks).
As the ESP32-C3-WROOM adapter is also suitable for the ESP-WROOM-2 (ESP8266) modules, but with different pin names, I would like to copy and edit the [ESP32-C3-WROOM_flexypin](https://github.com/solderparty/flexypin_adapters_hw/tree/main/ESP32-C3-WROOM_flexypin) KiCad project. And of course contribute that back via a pull request. This would also allow me to simple print the edited board layout and make a sticker from that to apply to one of my ESP32-C3-WROOM adapters :).

The problem I encounter is that I can't open the KiCad files;

When I try to open the schematic:
> KiCad was unable to open this file because it was created with a more recent version than the one you are running.
> 
> To open it you will need to upgrade KiCad to a version dated 20220104 or later.

Opening the board file crashes the program:
> Cannot interpret date code 20221232 in ....

I'm however running the latest stable release;
> Application: KiCad (64-bit)
> Version: (6.0.4), release build
> Build Info:
>     Date: Mar 18 2022 03:04:44

**Comment by arturo182** [comment]
Hi,

Sorry about that, the boards were designed using KiCad nightly, you can get the latest version  here: https://downloads.kicad.org/kicad/windows/explore/nightlies or https://downloads.kicad.org/kicad/macos/explore/nightlies, for Linux it depends on your distro.

It should be possible to open them in stable with some manual changes to the pcb files using a text editor, I'm planning on doing it, just haven't gotten to it yet 😣

**Comment by Maff-** [comment]
Thanks for the response. I figured as much :), after creating this issue I found https://forum.kicad.info/t/version-compatibility-and-file-transferability/33768. I'll give manual editing a try over the weekend.
